require("prototypes.categories.usefulcombinators")
require("prototypes.categories.changes")
require("prototypes.entity.entities")
require("prototypes.item.items")
require("prototypes.signal.signal")
require("prototypes.recipe.recipes")
require("prototypes.technology.technology")
