data:extend(
{ 
  {
    type = "item",
    name = "timer-combinator",
    icon = "__UsefulCombinators__/graphics/icons/timer-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="timer-combinator",
    order = "b[combinators]-u[timer-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "counting-combinator",
    icon = "__UsefulCombinators__/graphics/icons/counting-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="counting-combinator",
    order = "b[combinators]-u[counting-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "random-combinator",
    icon = "__UsefulCombinators__/graphics/icons/random-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="random-combinator",
    order = "b[combinators]-u[random-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "color-combinator",
    icon = "__UsefulCombinators__/graphics/icons/color-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="color-combinator",
    order = "b[combinators]-u[color-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "comparator-combinator",
    icon = "__UsefulCombinators__/graphics/icons/comparator-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="comparator-combinator",
    order = "b[combinators]-u[comparator-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "converter-combinator",
    icon = "__UsefulCombinators__/graphics/icons/converter-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="converter-combinator",
    order = "b[combinators]-u[converter-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "min-combinator",
    icon = "__UsefulCombinators__/graphics/icons/min-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="min-combinator",
    order = "b[combinators]-u[min-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "max-combinator",
    icon = "__UsefulCombinators__/graphics/icons/max-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="max-combinator",
    order = "b[combinators]-u[max-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "and-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/and-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="and-gate-combinator",
    order = "b[combinators]-u[and-gate-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "or-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/or-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="or-gate-combinator",
    order = "b[combinators]-u[or-gate-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "not-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/not-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="not-gate-combinator",
    order = "b[combinators]-u[not-gate-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "nand-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/nand-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="nand-gate-combinator",
    order = "b[combinators]-u[nand-gate-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "nor-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/nor-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="nor-gate-combinator",
    order = "b[combinators]-u[nor-gate-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "xor-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/xor-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="xor-gate-combinator",
    order = "b[combinators]-u[xor-gate-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "xnor-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/xnor-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="xnor-gate-combinator",
    order = "b[combinators]-u[xnor-gate-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "detector-combinator",
    icon = "__UsefulCombinators__/graphics/icons/detector-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="detector-combinator",
    order = "b[combinators]-u[detector-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "sensor-combinator",
    icon = "__UsefulCombinators__/graphics/icons/sensor-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="sensor-combinator",
    order = "b[combinators]-u[sensor-combinator]",
    stack_size= 10,
  },
  {
    type = "item",
    name = "railway-combinator",
    icon = "__UsefulCombinators__/graphics/icons/railway-combinator.png",
    flags = { "goes-to-quickbar" },
    subgroup = "circuit-network",
    place_result="railway-combinator",
    order = "b[combinators]-u[railway-combinator]",
    stack_size= 10,
  }
}) 