data:extend(
{ 
  {
    type = "item",
    name = "timer-combinator",
    icon = "__UsefulCombinators__/graphics/icons/timer-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "main",
    place_result="timer-combinator",
    order = "a[timer]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "counting-combinator",
    icon = "__UsefulCombinators__/graphics/icons/counting-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "main",
    place_result="counting-combinator",
    order = "b[counting]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "random-combinator",
    icon = "__UsefulCombinators__/graphics/icons/random-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "main",
    place_result="random-combinator",
    order = "c[random]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "color-combinator",
    icon = "__UsefulCombinators__/graphics/icons/color-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "other",
    place_result="color-combinator",
    order = "e[color]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "comparator-combinator",
    icon = "__UsefulCombinators__/graphics/icons/comparator-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "main",
    place_result="comparator-combinator",
    order = "d[comparator]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "converter-combinator",
    icon = "__UsefulCombinators__/graphics/icons/converter-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "other",
    place_result="converter-combinator",
    order = "a[converter]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "min-combinator",
    icon = "__UsefulCombinators__/graphics/icons/min-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "main",
    place_result="min-combinator",
    order = "f[min]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "max-combinator",
    icon = "__UsefulCombinators__/graphics/icons/max-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "main",
    place_result="max-combinator",
    order = "e[max]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "and-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/and-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "logic-gates",
    place_result="and-gate-combinator",
    order = "a[and]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "or-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/or-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "logic-gates",
    place_result="or-gate-combinator",
    order = "o[or]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "not-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/not-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "logic-gates",
    place_result="not-gate-combinator",
    order = "n[not]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "nand-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/nand-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "logic-gates",
    place_result="nand-gate-combinator",
    order = "n[nand]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "nor-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/nor-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "logic-gates",
    place_result="nor-gate-combinator",
    order = "n[nor]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "xor-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/xor-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "logic-gates",
    place_result="xor-gate-combinator",
    order = "x[xor]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "xnor-gate-combinator",
    icon = "__UsefulCombinators__/graphics/icons/xnor-gate-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "logic-gates",
    place_result="xnor-gate-combinator",
    order = "x[xnor]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "detector-combinator",
    icon = "__UsefulCombinators__/graphics/icons/detector-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "other",
    place_result="detector-combinator",
    order = "b[detector]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "sensor-combinator",
    icon = "__UsefulCombinators__/graphics/icons/sensor-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "other",
    place_result="sensor-combinator",
    order = "c[sensor]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "railway-combinator",
    icon = "__UsefulCombinators__/graphics/icons/railway-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "other",
    place_result="railway-combinator",
    order = "d[railway]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "emitter-combinator",
    icon = "__UsefulCombinators__/graphics/icons/emitter-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "other",
    place_result="emitter-combinator",
    order = "f[emitter]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "receiver-combinator",
    icon = "__UsefulCombinators__/graphics/icons/receiver-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "other",
    place_result="receiver-combinator",
    order = "g[receiver]",
    stack_size= 50,
  },
  {
    type = "item",
    name = "power-combinator",
    icon = "__UsefulCombinators__/graphics/icons/power-combinator.png",
    flags = { "goes-to-quickbar" },
    group = "useful-combinators",
    subgroup = "other2",
    place_result="power-combinator",
    order = "a[power]",
    stack_size= 50,
  }
}) 